permissions:
  contents: write
name: Generate Daily Key

on:
  schedule:
    - cron: '0 16 * * *'  # 12 midnight PH time (UTC+8)
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Generate Key with Retry
        run: |
          pip install --upgrade pip
          mkdir -p keys
          ATTEMPTS=0
          MAX_ATTEMPTS=5
          until python generatekey.py
          do
            ATTEMPTS=$((ATTEMPTS+1))
            if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
              echo "Key generation failed after $MAX_ATTEMPTS attempts."
              exit 1
            fi
            echo "Key generation failed. Retrying in 10 seconds..."
            sleep 10
          done
      - name: Commit and Push Keys
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add keys/
          git commit -m "Add key for $(date -u -d '+8 hours' +'%Y-%m-%d')" || echo "No changes to commit"
          git push
